#!/bin/sh

xsetroot -cursor_name left_ptr

bspc config split_ratio           0.5
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config border_width          4
bspc config window_gap            16
bspc config normal_border_color   \#585c78
bspc config focused_border_color  \#bcbfb9
bspc config presel_feedback_color \#bcbfb9
bspc config top_padding           32
bspc monitor -d code etc web
bspc desktop web -l monocle
bspc config borderless_monocle    true
bspc config gapless_monocle       true

sxhkd &
feh --bg-fill ~/pictures/beach.jpg
compton -b --config ~/.config/compton.conf
~/.config/lemonbar/info | lemonbar -p \
    -g x32 \
    -B \#1f2033 \
    -F \#d4cec2 \
    -f "-*-proggysquare-*-*-*-*-*-*-*-*-*-*-*-*" &
urxvtd -q -o -f
redshift -l 30:31 -b 0.7 &
